version: 2.1
workflows:
  install_build_only:
    jobs:
      - yarn:
          context: heycar
      - yarn_test:
          context: heycar
          requires:
            - yarn
      - yarn_build:
          context: heycar
          requires:
            - yarn
jobs:
  yarn:
    docker:
      - image: node:14.10-slim
    steps:
      - add_ssh_keys:
          fingerprints:
            - ${GIT_CHECKOUT_SSH_KEY_FINGERPRINT}
      - run: apt-get update && apt-get install -y ca-certificates git
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run: 
          name: 'Install Dependencies'
          command: yarn install --frozen-lockfile
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
  yarn_test: 
    docker:
      - image: node:14.10-slim
    steps:
        - run: apt-get update && apt-get install -y ca-certificates git
        - attach_workspace: 
            at: .
        - run:
            name: Unit Test Cases
            command: |
              echo "Command to run test cases will go here."
  yarn_build: 
    docker:
      - image: node:14.10-slim
    steps:
        - run: apt-get update && apt-get install -y ca-certificates git
        - attach_workspace: 
            at: .
        - run: 
            name: Build the Next Js project
            command: next build
        - save_cache:
            paths:
              - node_modules
            key: v1-dependencies-{{ checksum "package.json" }}